# Site settings
title: Glenn Dreams of Code
email: glenn@gespinosa.org
description: > # this means to ignore newlines until "baseurl:"
  Adventures of a nurse turned hacker/programmer. Features articles regarding coding, nursing, and random musing - also occasional essays on topics I'm interested in, which could pretty much be anything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gespinosa.org" # the base hostname & protocol for your site
twitter_username: gpespn
github_username:  gxespino

# Build settings
markdown: kramdown
