name: Glenn Dreams of Code
description: Code, Ruby, Musings, etc.
meta_description: "A nurse/hackers site about programming and healthcare"

aboutPage: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]

highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://gespinosa.org'
disqus: true
disqus_shortname: 'glennespinosa'

# Details for the RSS feed generator
url:            'http://gespinosa.org'
author:         'Glenn Espinosa'
authorTwitter:  'gpespn'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
