name: Glenn Espinosa
description: Musings of a software artisan

aboutPage: true

redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]

highlighter: # rouge

plugins: [rouge, jekyll-paginate]

paginate: 10
baseurl: '/'
domain_name: 'http://glennespinosa.com'
disqus: true
disqus_shortname: 'glennespinosa'

# Details for the RSS feed generator
url:            'http://glennespinosa.com'
author:         'Glenn Espinosa'
authorTwitter:  'gxespino'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
